### ISSUE TITLE
Private repository for exercises

### ISSUE THREAD

**Issue by vlopezj** [vlopezj/coq-course#11]
@AndreasLoow mentioned in the chat that the authors of the Software Foundations do not wish solutions to the exercises in the book to be published.

So we need a private repo to upload the exercise solutions.

**Comment by vlopezj** [comment]
It seems that bitbucket limits private repos to 5 users, so they are not an option.

I set up a repository on [Framasoft's Gitlab instance](http://framagit.org).

Every participant will shortly receive an invite by e-mail. You can then log in with your existing Github or Bitbucket account and get access to the repo.

You may need to authorize your SSH keys in order to push to the repo. Here's [the form](https://framagit.org/profile/keys) to authorize new SSH keys. You can quickly view the SSH keys authorized to your Github account at `https://github.com/<username>.keys`. For example: https://github.com/vlopezj.keys .

**Comment by dschoepe** [comment]
As discussed on IRC, I set up a private repo and added everyone as collaborators. Once #13 is resolved, I'll migrate it to the same organization.

**Comment by vlopezj** [comment]
Github organizations cannot have private repos (unless the owner pays). If that has any chance of working it should be someone with a linked Chalmers account that creates the organization. So I'll assign #13 to you.
